language: c

build:
    ci:
      - >
        if [ "${IS_GIT_TAG}" = "true" ]; then
          docker build -t docker.io/zephyrprojectrtos/zephyr-build:${GIT_TAG_NAME} .;
          docker build -t docker.io/zephyrprojectrtos/zephyr-build:latest .;
        else
          docker build -t docker.io/zephyrprojectrtos/zephyr-build:$BRANCH.$BUILD_NUMBER .;
        fi

    post_ci:
      - >
        if [ "${IS_GIT_TAG}" = "true" ]; then
          docker push docker.io/zephyrprojectrtos/zephyr-build:${GIT_TAG_NAME};
          docker push docker.io/zephyrprojectrtos/zephyr-build:latest;
        fi

integrations:
  hub:
    - integrationName: project_docker_repo
      type: docker
